// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd9X2OlF64Aq7qcFN0chZWS3DAkEqlf_8',
    appId: '1:758889203247:web:0ca8d57f7c00e615fd68da',
    messagingSenderId: '758889203247',
    projectId: 'firebase-flutter-final',
    authDomain: 'fir-flutter-final-20806.firebaseapp.com',
    storageBucket: 'firebase-flutter-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAavqkZ4-82vfAmNpVhSXkDOknamDex0Uk',
    appId: '1:758889203247:android:9ea001cb7c3209d0fd68da',
    messagingSenderId: '758889203247',
    projectId: 'firebase-flutter-final',
    storageBucket: 'firebase-flutter-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUalvv9fV5FtkhEuDgJdOzC94HM44zjz8',
    appId: '1:758889203247:ios:e54163885630e459fd68da',
    messagingSenderId: '758889203247',
    projectId: 'firebase-flutter-final',
    storageBucket: 'firebase-flutter-final.appspot.com',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUalvv9fV5FtkhEuDgJdOzC94HM44zjz8',
    appId: '1:758889203247:ios:c02f3288f260de3cfd68da',
    messagingSenderId: '758889203247',
    projectId: 'firebase-flutter-final',
    storageBucket: 'firebase-flutter-final.appspot.com',
    iosBundleId: 'com.example.flutterFinal.RunnerTests',
  );
}
